/**
 * Mock data for the Equity Builders platform.
 * 
 * This provides realistic, representative data for all modules.
 * In production, this would be replaced by database queries.
 * The data is designed to demonstrate real-world scenarios including:
 * - Properties at various stages of the pipeline
 * - Claims with different outcomes
 * - Contractors with varying track records
 * - Equity outcomes that show real value creation
 */

import type {
  User,
  Property,
  InsuranceClaim,
  Contractor,
  ContractorAssignment,
  EquityOutcome,
  AtosInsight,
  ActivityEntry,
  DashboardMetrics,
  Inspection,
  Evidence,
  CarrierInteraction,
} from '@/types';

// ─── Current User ──────────────────────────────────────────────

export const currentUser: User = {
  id: 'usr-001',
  email: 'marcus.reid@equitybuilders.com',
  name: 'Marcus Reid',
  role: 'internal',
  organization: 'Equity Builders',
  phone: '(555) 234-5678',
  createdAt: '2024-01-15T08:00:00Z',
  lastLoginAt: '2026-02-09T14:30:00Z',
};

// ─── Properties ────────────────────────────────────────────────

export const properties: Property[] = [
  {
    id: 'prop-001',
    name: 'Westfield Commerce Center',
    address: '4200 Commerce Blvd',
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    propertyType: 'commercial',
    status: 'in-repair',
    ownerId: 'usr-010',
    ownerName: 'Westfield Properties LLC',
    squareFootage: 45000,
    yearBuilt: 1998,
    estimatedValue: 3200000,
    damageDate: '2025-10-15',
    damageClassifications: ['wind', 'roof', 'water'],
    createdAt: '2025-10-20T10:00:00Z',
    updatedAt: '2026-02-01T15:30:00Z',
  },
  {
    id: 'prop-002',
    name: 'Oakmont Business Park - Building A',
    address: '780 Oakmont Dr, Suite 100',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76102',
    propertyType: 'commercial',
    status: 'claim-review',
    ownerId: 'usr-011',
    ownerName: 'Oakmont Investments',
    squareFootage: 28000,
    yearBuilt: 2005,
    estimatedValue: 2100000,
    damageDate: '2025-11-02',
    damageClassifications: ['hail', 'roof', 'facade'],
    createdAt: '2025-11-05T09:00:00Z',
    updatedAt: '2026-01-28T11:00:00Z',
  },
  {
    id: 'prop-003',
    name: 'Riverside Industrial Complex',
    address: '1500 River Rd',
    city: 'Arlington',
    state: 'TX',
    zip: '76010',
    propertyType: 'industrial',
    status: 'inspection',
    ownerId: 'usr-012',
    ownerName: 'Riverside Holdings',
    squareFootage: 72000,
    yearBuilt: 1992,
    estimatedValue: 4800000,
    damageDate: '2026-01-10',
    damageClassifications: ['wind', 'structural', 'roof'],
    createdAt: '2026-01-12T14:00:00Z',
    updatedAt: '2026-02-05T09:30:00Z',
  },
  {
    id: 'prop-004',
    name: 'Heritage Plaza Offices',
    address: '320 Heritage Way',
    city: 'Plano',
    state: 'TX',
    zip: '75024',
    propertyType: 'commercial',
    status: 'complete',
    ownerId: 'usr-013',
    ownerName: 'Heritage Group',
    squareFootage: 35000,
    yearBuilt: 2010,
    estimatedValue: 2800000,
    damageDate: '2025-06-20',
    damageClassifications: ['hail', 'roof'],
    createdAt: '2025-06-25T08:00:00Z',
    updatedAt: '2025-12-15T16:00:00Z',
  },
  {
    id: 'prop-005',
    name: 'Meridian Mixed-Use Tower',
    address: '900 Meridian Ave',
    city: 'Dallas',
    state: 'TX',
    zip: '75202',
    propertyType: 'mixed-use',
    status: 'claim-filed',
    ownerId: 'usr-014',
    ownerName: 'Meridian Development Corp',
    squareFootage: 120000,
    yearBuilt: 2015,
    estimatedValue: 12500000,
    damageDate: '2025-12-28',
    damageClassifications: ['wind', 'water', 'facade', 'roof'],
    createdAt: '2026-01-02T10:00:00Z',
    updatedAt: '2026-02-08T14:00:00Z',
  },
  {
    id: 'prop-006',
    name: 'Summit Ridge Apartments',
    address: '2100 Summit Ridge Pkwy',
    city: 'Irving',
    state: 'TX',
    zip: '75038',
    propertyType: 'multi-family',
    status: 'approved',
    ownerId: 'usr-015',
    ownerName: 'Summit Ridge Partners',
    squareFootage: 85000,
    yearBuilt: 2001,
    estimatedValue: 6200000,
    damageDate: '2025-09-15',
    damageClassifications: ['hail', 'roof', 'water', 'hvac'],
    createdAt: '2025-09-18T11:00:00Z',
    updatedAt: '2026-02-03T10:00:00Z',
  },
];

// ─── Inspections ───────────────────────────────────────────────

export const inspections: Inspection[] = [
  {
    id: 'insp-001',
    propertyId: 'prop-001',
    type: 'initial',
    inspectorName: 'James Thornton',
    inspectorId: 'usr-020',
    date: '2025-10-22',
    findings: 'Significant wind damage to roof membrane. Multiple areas of ponding water. HVAC units displaced. East facade shows impact damage consistent with wind-borne debris.',
    damageClassifications: ['wind', 'roof', 'water'],
    severityScore: 7,
    photos: [],
    documents: [],
    createdAt: '2025-10-22T16:00:00Z',
  },
  {
    id: 'insp-002',
    propertyId: 'prop-003',
    type: 'initial',
    inspectorName: 'Sarah Kim',
    inspectorId: 'usr-021',
    date: '2026-01-15',
    findings: 'Structural damage to north wall. Roof sections compromised with visible daylight penetration. Metal siding torn in multiple locations. Foundation shows stress fractures that may predate the storm event — further engineering assessment recommended.',
    damageClassifications: ['wind', 'structural', 'roof'],
    severityScore: 9,
    photos: [],
    documents: [],
    createdAt: '2026-01-15T17:00:00Z',
  },
  {
    id: 'insp-003',
    propertyId: 'prop-005',
    type: 'initial',
    inspectorName: 'James Thornton',
    inspectorId: 'usr-020',
    date: '2026-01-05',
    findings: 'High-rise facade damage on floors 8-15. Window seals compromised. Water intrusion evidence in multiple units. Roof parapet wall damage. Elevator mechanical room flooded.',
    damageClassifications: ['wind', 'water', 'facade', 'roof'],
    severityScore: 8,
    photos: [],
    documents: [],
    createdAt: '2026-01-05T15:00:00Z',
  },
];

// ─── Insurance Claims ──────────────────────────────────────────

export const insuranceClaims: InsuranceClaim[] = [
  {
    id: 'clm-001',
    propertyId: 'prop-001',
    propertyName: 'Westfield Commerce Center',
    claimNumber: 'WCC-2025-4421',
    carrier: 'National Property Insurance',
    policyNumber: 'NPI-COM-887234',
    status: 'approved',
    filedDate: '2025-10-25',
    amountClaimed: 485000,
    amountApproved: 412000,
    amountPaid: 412000,
    adjusterName: 'Patricia Wells',
    adjusterContact: 'p.wells@npi-insurance.com',
    scopeDiscrepancy: 15,
    interactions: [],
    createdAt: '2025-10-25T10:00:00Z',
    updatedAt: '2025-12-10T14:00:00Z',
  },
  {
    id: 'clm-002',
    propertyId: 'prop-002',
    propertyName: 'Oakmont Business Park - Building A',
    claimNumber: 'OBP-2025-7823',
    carrier: 'Southwest Commercial Mutual',
    policyNumber: 'SCM-2024-443891',
    status: 'under-review',
    filedDate: '2025-11-10',
    amountClaimed: 315000,
    adjusterName: 'Robert Chen',
    adjusterContact: 'r.chen@swcmutual.com',
    interactions: [],
    createdAt: '2025-11-10T09:00:00Z',
    updatedAt: '2026-01-28T11:00:00Z',
  },
  {
    id: 'clm-003',
    propertyId: 'prop-005',
    propertyName: 'Meridian Mixed-Use Tower',
    claimNumber: 'MMT-2026-0112',
    carrier: 'Metropolitan Underwriters',
    policyNumber: 'MU-HVP-2025-12001',
    status: 'filed',
    filedDate: '2026-01-08',
    amountClaimed: 1850000,
    adjusterName: 'Pending Assignment',
    interactions: [],
    createdAt: '2026-01-08T10:00:00Z',
    updatedAt: '2026-02-08T14:00:00Z',
  },
  {
    id: 'clm-004',
    propertyId: 'prop-004',
    propertyName: 'Heritage Plaza Offices',
    claimNumber: 'HPO-2025-3392',
    carrier: 'National Property Insurance',
    policyNumber: 'NPI-COM-556712',
    status: 'settled',
    filedDate: '2025-07-01',
    amountClaimed: 220000,
    amountApproved: 195000,
    amountPaid: 195000,
    adjusterName: 'Michelle Torres',
    adjusterContact: 'm.torres@npi-insurance.com',
    scopeDiscrepancy: 11,
    interactions: [],
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2025-10-20T16:00:00Z',
  },
  {
    id: 'clm-005',
    propertyId: 'prop-006',
    propertyName: 'Summit Ridge Apartments',
    claimNumber: 'SRA-2025-9901',
    carrier: 'Allied Property Group',
    policyNumber: 'APG-MF-2025-33100',
    status: 'approved',
    filedDate: '2025-09-25',
    amountClaimed: 720000,
    amountApproved: 680000,
    adjusterName: 'David Marsh',
    adjusterContact: 'd.marsh@alliedpg.com',
    scopeDiscrepancy: 5.5,
    interactions: [],
    createdAt: '2025-09-25T11:00:00Z',
    updatedAt: '2026-02-03T10:00:00Z',
  },
];

// ─── Contractors ───────────────────────────────────────────────

export const contractors: Contractor[] = [
  {
    id: 'ctr-001',
    companyName: 'Apex Roofing & Restoration',
    contactName: 'Daniel Brooks',
    email: 'dbrooks@apexrr.com',
    phone: '(555) 901-2345',
    licenseNumber: 'TX-RR-44521',
    insuranceVerified: true,
    specialties: ['Commercial Roofing', 'Storm Restoration', 'Waterproofing'],
    status: 'active',
    rating: 4.8,
    completedProjects: 34,
    activeAssignments: 2,
    createdAt: '2024-06-15T10:00:00Z',
  },
  {
    id: 'ctr-002',
    companyName: 'Metro Structural Solutions',
    contactName: 'Lisa Huang',
    email: 'lhuang@metross.com',
    phone: '(555) 234-6789',
    licenseNumber: 'TX-GC-78812',
    insuranceVerified: true,
    specialties: ['Structural Repair', 'Foundation Work', 'Commercial Construction'],
    status: 'active',
    rating: 4.9,
    completedProjects: 28,
    activeAssignments: 1,
    createdAt: '2024-03-10T08:00:00Z',
  },
  {
    id: 'ctr-003',
    companyName: 'ClearView Facade Systems',
    contactName: 'Mark Patterson',
    email: 'mpatterson@clearviewfs.com',
    phone: '(555) 567-8901',
    licenseNumber: 'TX-SC-33245',
    insuranceVerified: true,
    specialties: ['Facade Restoration', 'Window Systems', 'Curtain Wall'],
    status: 'active',
    rating: 4.6,
    completedProjects: 19,
    activeAssignments: 1,
    createdAt: '2024-09-20T14:00:00Z',
  },
  {
    id: 'ctr-004',
    companyName: 'ProTech HVAC Commercial',
    contactName: 'Kevin Wells',
    email: 'kwells@protechhvac.com',
    phone: '(555) 345-6712',
    licenseNumber: 'TX-HVAC-91100',
    insuranceVerified: true,
    specialties: ['Commercial HVAC', 'Mechanical Systems', 'Energy Optimization'],
    status: 'active',
    rating: 4.7,
    completedProjects: 42,
    activeAssignments: 3,
    createdAt: '2024-01-05T09:00:00Z',
  },
  {
    id: 'ctr-005',
    companyName: 'Lone Star Waterproofing',
    contactName: 'Amanda Garcia',
    email: 'agarcia@lswp.com',
    phone: '(555) 789-0123',
    licenseNumber: 'TX-WP-55672',
    insuranceVerified: false,
    specialties: ['Waterproofing', 'Moisture Remediation', 'Interior Restoration'],
    status: 'pending',
    rating: undefined,
    completedProjects: 0,
    activeAssignments: 0,
    createdAt: '2026-01-20T10:00:00Z',
  },
];

// ─── Contractor Assignments ────────────────────────────────────

export const assignments: ContractorAssignment[] = [
  {
    id: 'asgn-001',
    contractorId: 'ctr-001',
    contractorName: 'Apex Roofing & Restoration',
    propertyId: 'prop-001',
    propertyName: 'Westfield Commerce Center',
    scope: 'Full roof membrane replacement, flashing repair, and drainage system restoration. Includes removal of damaged HVAC mounting curbs and waterproofing of all penetrations.',
    status: 'in-progress',
    estimatedCost: 285000,
    startDate: '2026-01-10',
    estimatedEndDate: '2026-03-15',
    complianceScore: 94,
    progressPercent: 62,
    createdAt: '2025-12-15T10:00:00Z',
    updatedAt: '2026-02-08T16:00:00Z',
  },
  {
    id: 'asgn-002',
    contractorId: 'ctr-002',
    contractorName: 'Metro Structural Solutions',
    propertyId: 'prop-001',
    propertyName: 'Westfield Commerce Center',
    scope: 'East facade structural repair. Remove and replace damaged panels. Reinforce connection points. Install new weather barrier system.',
    status: 'in-progress',
    estimatedCost: 127000,
    startDate: '2026-01-20',
    estimatedEndDate: '2026-02-28',
    complianceScore: 97,
    progressPercent: 78,
    createdAt: '2026-01-05T14:00:00Z',
    updatedAt: '2026-02-07T11:00:00Z',
  },
  {
    id: 'asgn-003',
    contractorId: 'ctr-003',
    contractorName: 'ClearView Facade Systems',
    propertyId: 'prop-005',
    propertyName: 'Meridian Mixed-Use Tower',
    scope: 'Facade panel replacement floors 8-15. Window seal replacement for 47 units. Curtain wall joint resealing.',
    status: 'pending',
    estimatedCost: 890000,
    complianceScore: undefined,
    progressPercent: 0,
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-02-01T09:00:00Z',
  },
];

// ─── Equity Outcomes ───────────────────────────────────────────

export const equityOutcomes: EquityOutcome[] = [
  {
    id: 'eq-001',
    propertyId: 'prop-004',
    propertyName: 'Heritage Plaza Offices',
    propertyAddress: '320 Heritage Way, Plano, TX 75024',
    valueBefore: 2800000,
    valueAfter: 3150000,
    insurancePayout: 195000,
    repairCost: 178000,
    equityGain: 350000,
    equityGainPercent: 12.5,
    narrative: 'Heritage Plaza underwent comprehensive hail damage restoration including full roof replacement with upgraded impact-resistant materials. The insurance-funded repairs, combined with strategic material upgrades, resulted in a verified $350,000 equity gain. The property now features a 30-year warranted roof system, significantly reducing future maintenance liability and improving insurability.',
    status: 'verified',
    verifiedBy: 'Marcus Reid',
    verifiedAt: '2025-12-15T16:00:00Z',
    createdAt: '2025-11-30T10:00:00Z',
    updatedAt: '2025-12-15T16:00:00Z',
  },
  {
    id: 'eq-002',
    propertyId: 'prop-001',
    propertyName: 'Westfield Commerce Center',
    propertyAddress: '4200 Commerce Blvd, Dallas, TX 75201',
    valueBefore: 3200000,
    valueAfter: 3800000,
    insurancePayout: 412000,
    repairCost: 395000,
    equityGain: 600000,
    equityGainPercent: 18.75,
    narrative: 'In-progress restoration. Projected equity gain based on current scope execution and comparable market analysis. Final verification pending completion of roof and facade work.',
    status: 'draft',
    createdAt: '2026-01-15T14:00:00Z',
    updatedAt: '2026-02-08T10:00:00Z',
  },
  {
    id: 'eq-003',
    propertyId: 'prop-006',
    propertyName: 'Summit Ridge Apartments',
    propertyAddress: '2100 Summit Ridge Pkwy, Irving, TX 75038',
    valueBefore: 6200000,
    valueAfter: 7100000,
    insurancePayout: 680000,
    repairCost: 0,
    equityGain: 900000,
    equityGainPercent: 14.5,
    narrative: 'Pending contractor mobilization. Equity projection based on approved claim amount and planned scope of work including full roof replacement, HVAC unit replacement, and water damage remediation across 12 units.',
    status: 'calculating',
    createdAt: '2026-02-05T09:00:00Z',
    updatedAt: '2026-02-05T09:00:00Z',
  },
];

// ─── ATOS Insights ─────────────────────────────────────────────

export const atosInsights: AtosInsight[] = [
  {
    id: 'insight-001',
    title: 'Scope Discrepancy Detected — Oakmont Business Park',
    description: 'The carrier\'s preliminary scope excludes facade damage documented in the initial inspection. This represents approximately $45,000 in uncovered repairs. Recommend filing a supplemental claim with inspection photos OBP-FACADE-001 through OBP-FACADE-012 as supporting evidence.',
    severity: 'critical',
    module: 'insurance',
    entityId: 'clm-002',
    entityType: 'claim',
    actionLabel: 'Review Discrepancy',
    actionUrl: '/insurance/clm-002',
    dismissed: false,
    createdAt: '2026-02-08T10:00:00Z',
  },
  {
    id: 'insight-002',
    title: 'Contractor Insurance Expiring — Apex Roofing',
    description: 'Apex Roofing & Restoration\'s general liability insurance expires on March 1, 2026. They have 2 active assignments. Ensure renewal documentation is received before expiration to maintain compliance on the Westfield Commerce Center project.',
    severity: 'warning',
    module: 'contractors',
    entityId: 'ctr-001',
    entityType: 'contractor',
    actionLabel: 'View Contractor',
    actionUrl: '/contractors/ctr-001',
    dismissed: false,
    createdAt: '2026-02-07T14:00:00Z',
  },
  {
    id: 'insight-003',
    title: 'Equity Opportunity — Meridian Mixed-Use Tower',
    description: 'Based on the claim amount ($1.85M) and comparable property improvements in the 75202 zip code, this property has potential for a 15-22% equity gain if strategic material upgrades are specified in the repair scope. This could translate to $1.8M–$2.7M in added value.',
    severity: 'opportunity',
    module: 'equity',
    entityId: 'prop-005',
    entityType: 'property',
    actionLabel: 'View Property',
    actionUrl: '/properties/prop-005',
    dismissed: false,
    createdAt: '2026-02-06T09:00:00Z',
  },
  {
    id: 'insight-004',
    title: 'Inspection Follow-Up Overdue — Riverside Industrial',
    description: 'The initial inspection for Riverside Industrial Complex flagged potential pre-existing foundation issues (severity 9/10). A structural engineering assessment was recommended but has not been scheduled. This could impact claim eligibility if not addressed promptly.',
    severity: 'critical',
    module: 'properties',
    entityId: 'prop-003',
    entityType: 'property',
    actionLabel: 'Schedule Assessment',
    actionUrl: '/properties/prop-003',
    dismissed: false,
    createdAt: '2026-02-05T11:00:00Z',
  },
  {
    id: 'insight-005',
    title: 'Claim Processing Ahead of Schedule — Westfield',
    description: 'National Property Insurance approved the Westfield Commerce Center claim 18 days faster than their average for commercial claims of this size. The full $412,000 has been disbursed. Repairs are on track with 62% completion.',
    severity: 'info',
    module: 'insurance',
    entityId: 'clm-001',
    entityType: 'claim',
    actionLabel: 'View Claim',
    actionUrl: '/insurance/clm-001',
    dismissed: false,
    createdAt: '2026-02-04T08:00:00Z',
  },
];

// ─── Recent Activity ───────────────────────────────────────────

export const recentActivity: ActivityEntry[] = [
  {
    id: 'act-001',
    type: 'inspection',
    title: 'Inspection Report Uploaded',
    description: 'Initial inspection report for Riverside Industrial Complex uploaded by Sarah Kim. Severity: 9/10.',
    entityId: 'insp-002',
    entityUrl: '/properties/prop-003',
    timestamp: '2026-02-09T14:00:00Z',
    userId: 'usr-021',
    userName: 'Sarah Kim',
  },
  {
    id: 'act-002',
    type: 'contractor',
    title: 'Progress Update — Westfield Facade',
    description: 'Metro Structural Solutions reported 78% completion on east facade repair. On track for Feb 28 deadline.',
    entityId: 'asgn-002',
    entityUrl: '/contractors/ctr-002',
    timestamp: '2026-02-09T11:30:00Z',
    userId: 'usr-030',
    userName: 'Lisa Huang',
  },
  {
    id: 'act-003',
    type: 'claim',
    title: 'Claim Filed — Meridian Tower',
    description: 'Insurance claim MMT-2026-0112 filed with Metropolitan Underwriters for $1,850,000.',
    entityId: 'clm-003',
    entityUrl: '/insurance/clm-003',
    timestamp: '2026-02-08T14:00:00Z',
    userId: 'usr-001',
    userName: 'Marcus Reid',
  },
  {
    id: 'act-004',
    type: 'property',
    title: 'New Property Added',
    description: 'Meridian Mixed-Use Tower added to the platform. Storm damage from Dec 28, 2025.',
    entityId: 'prop-005',
    entityUrl: '/properties/prop-005',
    timestamp: '2026-02-08T10:00:00Z',
    userId: 'usr-001',
    userName: 'Marcus Reid',
  },
  {
    id: 'act-005',
    type: 'equity',
    title: 'Equity Verification Complete',
    description: 'Heritage Plaza Offices equity gain of $350,000 (12.5%) verified and published.',
    entityId: 'eq-001',
    entityUrl: '/equity/eq-001',
    timestamp: '2026-02-07T16:00:00Z',
    userId: 'usr-001',
    userName: 'Marcus Reid',
  },
  {
    id: 'act-006',
    type: 'contractor',
    title: 'New Contractor Application',
    description: 'Lone Star Waterproofing submitted application. Insurance verification pending.',
    entityId: 'ctr-005',
    entityUrl: '/contractors/ctr-005',
    timestamp: '2026-02-06T10:00:00Z',
    userId: 'usr-040',
    userName: 'Amanda Garcia',
  },
];

// ─── Dashboard Metrics ─────────────────────────────────────────

export const dashboardMetrics: DashboardMetrics = {
  totalProperties: 6,
  activeInspections: 2,
  pendingClaims: 3,
  activeRepairs: 2,
  totalEquityGained: 1850000,
  avgClaimApprovalRate: 88.5,
  propertiesByStatus: {
    'intake': 0,
    'inspection': 1,
    'claim-filed': 1,
    'claim-review': 1,
    'approved': 1,
    'in-repair': 1,
    'verification': 0,
    'complete': 1,
    'disputed': 0,
  },
  recentActivity,
  atosInsights,
};
