/**
 * Mock Data Layer for Equity Builders
 *
 * This provides realistic data for development and demonstration.
 * In production, this is replaced by Postgres queries via the data access layer.
 *
 * Every piece of mock data is designed to tell a coherent story
 * about a real storm-damage-to-equity pipeline.
 */

import type {
  Property,
  InsuranceClaim,
  Contractor,
  ScopeAssignment,
  Evidence,
  Inspection,
  DamageArea,
  EquityOutcome,
  ATOSInsight,
  TimelineEvent,
  DashboardMetrics,
  User,
  CarrierInteraction,
} from "@/types";

// ─── Users ──────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: "usr_001",
    email: "marcus.reid@equitybuilders.com",
    name: "Marcus Reid",
    role: "internal",
    organizationId: "org_001",
    avatarUrl: null,
    createdAt: new Date("2024-01-15"),
    lastActiveAt: new Date("2026-02-09"),
  },
  {
    id: "usr_002",
    email: "sarah.chen@proprestore.com",
    name: "Sarah Chen",
    role: "owner",
    organizationId: null,
    avatarUrl: null,
    createdAt: new Date("2024-06-20"),
    lastActiveAt: new Date("2026-02-08"),
  },
  {
    id: "usr_003",
    email: "james.wilson@eliteroofing.com",
    name: "James Wilson",
    role: "contractor",
    organizationId: "org_002",
    avatarUrl: null,
    createdAt: new Date("2024-09-01"),
    lastActiveAt: new Date("2026-02-07"),
  },
  {
    id: "usr_004",
    email: "lisa.park@nationalinsurance.com",
    name: "Lisa Park",
    role: "adjuster",
    organizationId: "org_003",
    avatarUrl: null,
    createdAt: new Date("2025-01-10"),
    lastActiveAt: new Date("2026-02-06"),
  },
];

// ─── Properties ─────────────────────────────────────────────────────────────

export const mockProperties: Property[] = [
  {
    id: "prop_001",
    address: "4521 Commerce Parkway",
    city: "Dallas",
    state: "TX",
    zipCode: "75201",
    propertyType: "commercial",
    squareFootage: 28500,
    yearBuilt: 2005,
    ownerId: "usr_002",
    status: "restoration_active",
    preEventValue: 2850000,
    postRestorationValue: 3420000,
    stormEventDate: new Date("2025-10-15"),
    stormEventType: "Hail & Wind — Category 3",
    createdAt: new Date("2025-10-18"),
    updatedAt: new Date("2026-02-05"),
  },
  {
    id: "prop_002",
    address: "890 Industrial Boulevard",
    city: "Fort Worth",
    state: "TX",
    zipCode: "76102",
    propertyType: "industrial",
    squareFootage: 45000,
    yearBuilt: 1998,
    ownerId: "usr_002",
    status: "claim_in_progress",
    preEventValue: 4200000,
    postRestorationValue: null,
    stormEventDate: new Date("2025-11-02"),
    stormEventType: "Severe Hailstorm",
    createdAt: new Date("2025-11-05"),
    updatedAt: new Date("2026-02-01"),
  },
  {
    id: "prop_003",
    address: "1200 Greenville Ave, Suite 300",
    city: "Richardson",
    state: "TX",
    zipCode: "75080",
    propertyType: "commercial",
    squareFootage: 15200,
    yearBuilt: 2012,
    ownerId: "usr_002",
    status: "inspection_complete",
    preEventValue: 1950000,
    postRestorationValue: null,
    stormEventDate: new Date("2025-12-20"),
    stormEventType: "Wind Damage — Straight-line Winds",
    createdAt: new Date("2025-12-22"),
    updatedAt: new Date("2026-01-28"),
  },
  {
    id: "prop_004",
    address: "6789 Oak Lawn Ave",
    city: "Dallas",
    state: "TX",
    zipCode: "75219",
    propertyType: "mixed_use",
    squareFootage: 32000,
    yearBuilt: 2015,
    ownerId: "usr_002",
    status: "equity_realized",
    preEventValue: 5100000,
    postRestorationValue: 6375000,
    stormEventDate: new Date("2025-05-10"),
    stormEventType: "Hail & Wind — Category 4",
    createdAt: new Date("2025-05-12"),
    updatedAt: new Date("2026-01-15"),
  },
];

// ─── Inspections ────────────────────────────────────────────────────────────

const damageAreasProp1: DamageArea[] = [
  {
    id: "da_001",
    location: "Main Roof — North Section",
    classification: "hail",
    severity: "severe",
    description: "Extensive hail impact damage across 2,400 sq ft of TPO membrane. Multiple punctures and granule loss on modified bitumen sections.",
    estimatedRepairCost: 185000,
    evidenceIds: ["ev_001", "ev_002"],
  },
  {
    id: "da_002",
    location: "West Facade — Siding & Windows",
    classification: "wind",
    severity: "moderate",
    description: "Wind-driven debris impact on aluminum composite panels. Three window units compromised with broken seals.",
    estimatedRepairCost: 67000,
    evidenceIds: ["ev_003"],
  },
  {
    id: "da_003",
    location: "HVAC Units — Roof Level",
    classification: "hail",
    severity: "critical",
    description: "4 of 6 rooftop HVAC units show significant fin damage and housing dents. Unit efficiency reduced by estimated 35%.",
    estimatedRepairCost: 142000,
    evidenceIds: ["ev_004"],
  },
];

export const mockInspections: Inspection[] = [
  {
    id: "insp_001",
    propertyId: "prop_001",
    inspectorId: "usr_001",
    scheduledAt: new Date("2025-10-22"),
    completedAt: new Date("2025-10-22"),
    status: "completed",
    findings: "Significant storm damage consistent with Category 3 hail and wind event. Roof system requires full replacement. Multiple building systems affected. Total estimated damage exceeds $394,000.",
    damageAreas: damageAreasProp1,
    evidenceIds: ["ev_001", "ev_002", "ev_003", "ev_004", "ev_005"],
    createdAt: new Date("2025-10-20"),
  },
  {
    id: "insp_002",
    propertyId: "prop_002",
    inspectorId: "usr_001",
    scheduledAt: new Date("2025-11-10"),
    completedAt: new Date("2025-11-10"),
    status: "completed",
    findings: "Hail damage to standing seam metal roof system. Over 200 impact points documented. Gutter system destroyed. Interior water intrusion observed in warehouse section.",
    damageAreas: [
      {
        id: "da_004",
        location: "Metal Roof — Full Span",
        classification: "hail",
        severity: "severe",
        description: "200+ documented hail impact points on standing seam metal roof. Multiple panels require replacement.",
        estimatedRepairCost: 320000,
        evidenceIds: [],
      },
    ],
    evidenceIds: [],
    createdAt: new Date("2025-11-08"),
  },
  {
    id: "insp_003",
    propertyId: "prop_003",
    inspectorId: "usr_001",
    scheduledAt: new Date("2026-01-05"),
    completedAt: new Date("2026-01-05"),
    status: "completed",
    findings: "Wind damage to commercial office building. Partial roof membrane displacement, soffit damage, and compromised exterior sealing. Building envelope integrity reduced.",
    damageAreas: [
      {
        id: "da_005",
        location: "Roof Membrane — Southeast Corner",
        classification: "wind",
        severity: "moderate",
        description: "12x20 ft section of EPDM membrane displaced. Substrate exposed to elements.",
        estimatedRepairCost: 45000,
        evidenceIds: [],
      },
    ],
    evidenceIds: [],
    createdAt: new Date("2026-01-03"),
  },
];

// ─── Evidence ───────────────────────────────────────────────────────────────

export const mockEvidence: Evidence[] = [
  {
    id: "ev_001",
    propertyId: "prop_001",
    type: "photo",
    title: "Roof Hail Damage — North Section Overview",
    description: "Aerial drone photograph showing extent of hail impact across north roof section. Damage markers placed at impact points.",
    fileUrl: "/images/placeholder-evidence.jpg",
    thumbnailUrl: "/images/placeholder-thumb.jpg",
    uploadedById: "usr_001",
    tags: ["roof", "hail", "aerial", "damage-markers"],
    damageClassifications: ["hail", "roof"],
    capturedAt: new Date("2025-10-22T10:30:00"),
    uploadedAt: new Date("2025-10-22T14:00:00"),
    metadata: { camera: "DJI Mavic 3", resolution: "5280x3956", gpsLat: 32.7767, gpsLng: -96.797 },
  },
  {
    id: "ev_002",
    propertyId: "prop_001",
    type: "photo",
    title: "TPO Membrane Puncture Detail",
    description: "Close-up photograph of hail puncture through TPO membrane showing substrate exposure. Ruler placed for scale reference.",
    fileUrl: "/images/placeholder-evidence.jpg",
    thumbnailUrl: "/images/placeholder-thumb.jpg",
    uploadedById: "usr_001",
    tags: ["roof", "hail", "close-up", "tpo", "puncture"],
    damageClassifications: ["hail", "roof"],
    capturedAt: new Date("2025-10-22T10:45:00"),
    uploadedAt: new Date("2025-10-22T14:00:00"),
    metadata: { camera: "Canon EOS R5", resolution: "8192x5464" },
  },
  {
    id: "ev_003",
    propertyId: "prop_001",
    type: "photo",
    title: "West Facade Wind Damage",
    description: "Wind-driven debris impact damage to aluminum composite panel. Panel separation and substrate exposure visible.",
    fileUrl: "/images/placeholder-evidence.jpg",
    thumbnailUrl: "/images/placeholder-thumb.jpg",
    uploadedById: "usr_001",
    tags: ["facade", "wind", "siding", "debris-impact"],
    damageClassifications: ["wind", "siding"],
    capturedAt: new Date("2025-10-22T11:15:00"),
    uploadedAt: new Date("2025-10-22T14:00:00"),
    metadata: { camera: "Canon EOS R5", resolution: "8192x5464" },
  },
  {
    id: "ev_004",
    propertyId: "prop_001",
    type: "photo",
    title: "HVAC Unit #3 — Hail Damage",
    description: "Rooftop HVAC condenser unit showing severe fin damage from hail impact. Housing dented at multiple points.",
    fileUrl: "/images/placeholder-evidence.jpg",
    thumbnailUrl: "/images/placeholder-thumb.jpg",
    uploadedById: "usr_001",
    tags: ["hvac", "hail", "mechanical", "condenser"],
    damageClassifications: ["hail"],
    capturedAt: new Date("2025-10-22T11:30:00"),
    uploadedAt: new Date("2025-10-22T14:00:00"),
    metadata: { camera: "Canon EOS R5", resolution: "8192x5464" },
  },
  {
    id: "ev_005",
    propertyId: "prop_001",
    type: "document",
    title: "Forensic Inspection Report — Full Assessment",
    description: "Complete forensic inspection report documenting all damage areas, classifications, measurements, and photographic evidence references.",
    fileUrl: "/documents/placeholder-report.pdf",
    thumbnailUrl: null,
    uploadedById: "usr_001",
    tags: ["report", "forensic", "assessment", "complete"],
    damageClassifications: ["hail", "wind", "roof", "siding"],
    capturedAt: new Date("2025-10-25"),
    uploadedAt: new Date("2025-10-25"),
    metadata: { pages: 47, format: "PDF" },
  },
];

// ─── Insurance Claims ───────────────────────────────────────────────────────

export const mockClaims: InsuranceClaim[] = [
  {
    id: "clm_001",
    propertyId: "prop_001",
    claimNumber: "NI-2025-78432",
    carrierId: "carrier_001",
    carrierName: "National Insurance Group",
    policyNumber: "COM-2025-55891",
    dateOfLoss: new Date("2025-10-15"),
    dateFiled: new Date("2025-10-28"),
    status: "under_review",
    claimedAmount: 394000,
    approvedAmount: 245000,
    settledAmount: null,
    discrepancyAmount: 149000,
    adjusterAssignedId: "usr_004",
    notes: "Carrier initially approved partial scope. Supplement filed for HVAC and full roof replacement. Discrepancy under review.",
    createdAt: new Date("2025-10-28"),
    updatedAt: new Date("2026-02-01"),
  },
  {
    id: "clm_002",
    propertyId: "prop_002",
    claimNumber: "SW-2025-91205",
    carrierId: "carrier_002",
    carrierName: "Southwest Mutual",
    policyNumber: "IND-2025-33012",
    dateOfLoss: new Date("2025-11-02"),
    dateFiled: new Date("2025-11-15"),
    status: "additional_info_requested",
    claimedAmount: 520000,
    approvedAmount: null,
    settledAmount: null,
    discrepancyAmount: null,
    adjusterAssignedId: null,
    notes: "Carrier requested additional documentation of interior water damage and HVAC testing results.",
    createdAt: new Date("2025-11-15"),
    updatedAt: new Date("2026-01-28"),
  },
  {
    id: "clm_003",
    propertyId: "prop_004",
    claimNumber: "NI-2025-56123",
    carrierId: "carrier_001",
    carrierName: "National Insurance Group",
    policyNumber: "MU-2025-77201",
    dateOfLoss: new Date("2025-05-10"),
    dateFiled: new Date("2025-05-20"),
    status: "settled",
    claimedAmount: 890000,
    approvedAmount: 842000,
    settledAmount: 842000,
    discrepancyAmount: 48000,
    adjusterAssignedId: "usr_004",
    notes: "Claim settled after successful supplement negotiation. 94.6% of claimed amount recovered.",
    createdAt: new Date("2025-05-20"),
    updatedAt: new Date("2025-12-10"),
  },
];

// ─── Carrier Interactions ───────────────────────────────────────────────────

export const mockCarrierInteractions: CarrierInteraction[] = [
  {
    id: "ci_001",
    claimId: "clm_001",
    type: "inspection",
    date: new Date("2025-11-05"),
    summary: "Carrier adjuster conducted on-site inspection. Acknowledged roof damage but disputed HVAC scope.",
    initiatedBy: "carrier",
    contactName: "Robert Taylor",
    contactRole: "Field Adjuster",
    outcome: "Partial approval — roof damage acknowledged, HVAC denied pending additional documentation",
    attachmentIds: [],
    createdById: "usr_001",
    createdAt: new Date("2025-11-05"),
  },
  {
    id: "ci_002",
    claimId: "clm_001",
    type: "document_request",
    date: new Date("2025-11-20"),
    summary: "Submitted HVAC efficiency testing results and manufacturer specifications proving hail damage impact on unit performance.",
    initiatedBy: "internal",
    contactName: "Claims Department",
    contactRole: "Claims Processing",
    outcome: "Documents received and under review",
    attachmentIds: [],
    createdById: "usr_001",
    createdAt: new Date("2025-11-20"),
  },
  {
    id: "ci_003",
    claimId: "clm_001",
    type: "call",
    date: new Date("2026-01-15"),
    summary: "Follow-up call regarding supplement status. Carrier indicated review is ongoing. Escalation path discussed.",
    initiatedBy: "internal",
    contactName: "Lisa Park",
    contactRole: "Senior Adjuster",
    outcome: "Carrier committed to response within 15 business days",
    attachmentIds: [],
    createdById: "usr_001",
    createdAt: new Date("2026-01-15"),
  },
];

// ─── Contractors ────────────────────────────────────────────────────────────

export const mockContractors: Contractor[] = [
  {
    id: "ctr_001",
    companyName: "Elite Roofing & Restoration",
    contactName: "James Wilson",
    email: "james@eliteroofing.com",
    phone: "2145551234",
    licenseNumber: "TX-ROO-2024-5582",
    insuranceCertificateUrl: "/documents/placeholder-cert.pdf",
    specialties: ["commercial roofing", "TPO systems", "metal roofing", "storm restoration"],
    status: "active",
    rating: 4.8,
    completedProjects: 47,
    createdAt: new Date("2024-09-01"),
  },
  {
    id: "ctr_002",
    companyName: "Precision Exteriors LLC",
    contactName: "Maria Santos",
    email: "maria@precisionext.com",
    phone: "8175559876",
    licenseNumber: "TX-GEN-2023-8901",
    insuranceCertificateUrl: "/documents/placeholder-cert.pdf",
    specialties: ["facades", "siding", "windows", "building envelope"],
    status: "active",
    rating: 4.6,
    completedProjects: 31,
    createdAt: new Date("2024-11-15"),
  },
  {
    id: "ctr_003",
    companyName: "DFW Climate Systems",
    contactName: "David Kim",
    email: "david@dfwclimate.com",
    phone: "9725553456",
    licenseNumber: "TX-HVAC-2024-1234",
    insuranceCertificateUrl: "/documents/placeholder-cert.pdf",
    specialties: ["commercial HVAC", "rooftop units", "ductwork", "controls"],
    status: "active",
    rating: 4.9,
    completedProjects: 62,
    createdAt: new Date("2024-07-20"),
  },
];

// ─── Scope Assignments ──────────────────────────────────────────────────────

export const mockScopeAssignments: ScopeAssignment[] = [
  {
    id: "scope_001",
    propertyId: "prop_001",
    contractorId: "ctr_001",
    title: "Full Roof System Replacement",
    description: "Complete tear-off and replacement of TPO and modified bitumen roof systems. Includes insulation, membrane, flashing, and drainage.",
    lineItems: [
      { id: "li_001", description: "TPO membrane tear-off & disposal", quantity: 2400, unit: "sq ft", unitCost: 12, totalCost: 28800, status: "completed" },
      { id: "li_002", description: "New TPO membrane installation (60 mil)", quantity: 2400, unit: "sq ft", unitCost: 38, totalCost: 91200, status: "in_progress" },
      { id: "li_003", description: "Polyiso insulation board (R-30)", quantity: 2400, unit: "sq ft", unitCost: 8.5, totalCost: 20400, status: "completed" },
      { id: "li_004", description: "Perimeter & penetration flashing", quantity: 1, unit: "lot", unitCost: 18500, totalCost: 18500, status: "pending" },
      { id: "li_005", description: "Drainage system repair & testing", quantity: 1, unit: "lot", unitCost: 7200, totalCost: 7200, status: "pending" },
    ],
    status: "in_progress",
    totalAmount: 166100,
    startDate: new Date("2026-01-15"),
    estimatedCompletionDate: new Date("2026-03-15"),
    actualCompletionDate: null,
    complianceChecks: [
      { id: "cc_001", name: "Material specifications verified", description: "Confirm materials match approved scope", status: "passed", checkedAt: new Date("2026-01-14"), checkedById: "usr_001", notes: null },
      { id: "cc_002", name: "Permits obtained", description: "All required city/county permits in place", status: "passed", checkedAt: new Date("2026-01-12"), checkedById: "usr_001", notes: "Permit #2026-COM-4421" },
      { id: "cc_003", name: "Progress photo documentation", description: "Daily photo documentation of work progress", status: "pending", checkedAt: null, checkedById: null, notes: null },
    ],
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-02-05"),
  },
];

// ─── Equity Outcomes ────────────────────────────────────────────────────────

export const mockEquityOutcomes: EquityOutcome[] = [
  {
    id: "eq_001",
    propertyId: "prop_004",
    preEventValue: 5100000,
    postRestorationValue: 6375000,
    totalClaimAmount: 890000,
    totalInsurancePayout: 842000,
    totalRestorationCost: 756000,
    netEquityGain: 1361000,
    equityGainPercentage: 26.7,
    narrative: "The storm event at 6789 Oak Lawn Ave created a significant restoration opportunity. Through precise forensic documentation and strategic claim negotiation, 94.6% of the claimed amount was recovered. The full restoration — including upgraded systems that exceeded pre-event specifications — resulted in a 26.7% equity gain. Key drivers: (1) Comprehensive damage documentation captured $48K in scope the carrier initially missed, (2) Restoration upgrades to code-plus specifications increased property value beyond pre-event baseline, (3) Strategic timing of restoration during favorable material pricing reduced costs by an estimated $43K.",
    generatedAt: new Date("2026-01-15"),
    verifiedAt: new Date("2026-01-20"),
    verifiedById: "usr_001",
  },
];

// ─── ATOS Insights ──────────────────────────────────────────────────────────

export const mockATOSInsights: ATOSInsight[] = [
  {
    id: "insight_001",
    propertyId: "prop_001",
    type: "risk",
    severity: "high",
    title: "Claim Discrepancy Alert: $149K Gap Detected",
    description: "The carrier's approved amount of $245,000 is $149,000 below the documented forensic assessment of $394,000. The primary dispute centers on HVAC replacement scope. Historical data suggests this carrier approves HVAC claims 73% of the time when efficiency testing documentation is provided.",
    actionableSteps: [
      "Submit HVAC efficiency test results within 5 business days",
      "Request a re-inspection with an independent engineer present",
      "Prepare a detailed line-item comparison showing carrier vs. forensic scope",
    ],
    reasoning: "A $149K discrepancy on a $394K claim represents a 37.8% gap. This exceeds the typical negotiation range of 10-20%. Without supplement documentation, this gap is unlikely to close through standard claims processing.",
    acknowledged: false,
    acknowledgedAt: null,
    createdAt: new Date("2026-02-01"),
  },
  {
    id: "insight_002",
    propertyId: "prop_002",
    type: "gap",
    severity: "medium",
    title: "Missing Documentation: Interior Water Damage Photos",
    description: "The carrier has requested interior water damage documentation for the industrial property at 890 Industrial Blvd. Current evidence library contains exterior-only photographs. Interior documentation is required to support the full claim scope.",
    actionableSteps: [
      "Schedule interior photo documentation within 48 hours",
      "Document water staining patterns on warehouse ceiling and walls",
      "Capture moisture meter readings at affected areas",
    ],
    reasoning: "Interior water damage from roof compromises is a critical claim component. Without this documentation, the carrier can legitimately reduce the scope by an estimated $85,000-$120,000.",
    acknowledged: false,
    acknowledgedAt: null,
    createdAt: new Date("2026-01-30"),
  },
  {
    id: "insight_003",
    propertyId: "prop_003",
    type: "opportunity",
    severity: "medium",
    title: "Code Upgrade Opportunity: Energy Efficiency Credits",
    description: "The 1200 Greenville Ave property's roof repair scope triggers Richardson city code requirement for energy efficiency upgrades. This mandatory upgrade is covered under the insurance claim as 'code compliance' — adding approximately $28,000 in additional covered scope.",
    actionableSteps: [
      "Verify current Richardson building code requirements for commercial roof repairs",
      "Include code-upgrade line items in the claim supplement",
      "Document current vs. required insulation R-values",
    ],
    reasoning: "Code upgrade requirements triggered by insured repairs are a legitimate claim expansion opportunity. The $28K in additional scope will not only be covered by insurance but will increase the property's energy efficiency rating, contributing to long-term value.",
    acknowledged: true,
    acknowledgedAt: new Date("2026-02-05"),
    createdAt: new Date("2026-01-25"),
  },
  {
    id: "insight_004",
    propertyId: null,
    type: "recommendation",
    severity: "low",
    title: "Portfolio Insight: Storm Season Preparation",
    description: "Based on your active property portfolio in the DFW region, the upcoming spring storm season (March-June) presents both risk and opportunity. Current portfolio has 2 properties with open claims and 1 in active restoration.",
    actionableSteps: [
      "Ensure all properties have current pre-storm baseline documentation",
      "Verify insurance policy renewal dates and coverage adequacy",
      "Pre-position contractor relationships for rapid response",
    ],
    reasoning: "Proactive storm preparation reduces claim filing time by an average of 12 days and increases claim recovery rates by approximately 15% based on historical data across similar portfolios.",
    acknowledged: false,
    acknowledgedAt: null,
    createdAt: new Date("2026-02-08"),
  },
];

// ─── Timeline Events ────────────────────────────────────────────────────────

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: "te_001",
    propertyId: "prop_001",
    type: "storm_event",
    title: "Storm Event Recorded",
    description: "Category 3 hail and wind event confirmed in Dallas, TX area. Property within documented impact zone.",
    date: new Date("2025-10-15"),
    actorId: null,
    actorName: "System",
    metadata: { stormType: "Hail & Wind", category: 3 },
  },
  {
    id: "te_002",
    propertyId: "prop_001",
    type: "property_intake",
    title: "Property Intake Completed",
    description: "Property at 4521 Commerce Parkway registered in the system. Initial assessment initiated.",
    date: new Date("2025-10-18"),
    actorId: "usr_001",
    actorName: "Marcus Reid",
    metadata: {},
  },
  {
    id: "te_003",
    propertyId: "prop_001",
    type: "inspection_scheduled",
    title: "Forensic Inspection Scheduled",
    description: "Full forensic inspection scheduled for October 22, 2025. Inspector: Marcus Reid.",
    date: new Date("2025-10-20"),
    actorId: "usr_001",
    actorName: "Marcus Reid",
    metadata: { inspectionId: "insp_001" },
  },
  {
    id: "te_004",
    propertyId: "prop_001",
    type: "inspection_completed",
    title: "Forensic Inspection Completed",
    description: "Comprehensive inspection completed. 3 damage areas identified. Total estimated damage: $394,000. 47-page forensic report generated.",
    date: new Date("2025-10-22"),
    actorId: "usr_001",
    actorName: "Marcus Reid",
    metadata: { inspectionId: "insp_001", damageAreas: 3, totalEstimate: 394000 },
  },
  {
    id: "te_005",
    propertyId: "prop_001",
    type: "claim_filed",
    title: "Insurance Claim Filed",
    description: "Claim NI-2025-78432 filed with National Insurance Group. Policy: COM-2025-55891.",
    date: new Date("2025-10-28"),
    actorId: "usr_001",
    actorName: "Marcus Reid",
    metadata: { claimId: "clm_001", claimNumber: "NI-2025-78432" },
  },
  {
    id: "te_006",
    propertyId: "prop_001",
    type: "carrier_inspection",
    title: "Carrier Inspection Conducted",
    description: "National Insurance Group field adjuster completed on-site inspection. Partial roof damage acknowledged. HVAC scope disputed.",
    date: new Date("2025-11-05"),
    actorId: null,
    actorName: "Robert Taylor (NIG)",
    metadata: { claimId: "clm_001" },
  },
  {
    id: "te_007",
    propertyId: "prop_001",
    type: "claim_update",
    title: "Partial Approval Received",
    description: "Carrier approved $245,000 of $394,000 claimed. Discrepancy of $149,000 primarily in HVAC and facade scope.",
    date: new Date("2025-11-15"),
    actorId: null,
    actorName: "National Insurance Group",
    metadata: { claimId: "clm_001", approvedAmount: 245000, discrepancy: 149000 },
  },
  {
    id: "te_008",
    propertyId: "prop_001",
    type: "supplement_filed",
    title: "Claim Supplement Filed",
    description: "Supplement documentation submitted including HVAC efficiency testing results and updated facade damage assessment.",
    date: new Date("2025-11-20"),
    actorId: "usr_001",
    actorName: "Marcus Reid",
    metadata: { claimId: "clm_001" },
  },
  {
    id: "te_009",
    propertyId: "prop_001",
    type: "restoration_started",
    title: "Restoration Work Commenced",
    description: "Elite Roofing & Restoration began roof tear-off and replacement. Scope: Full roof system replacement ($166,100).",
    date: new Date("2026-01-15"),
    actorId: "usr_003",
    actorName: "James Wilson",
    metadata: { scopeId: "scope_001", contractorId: "ctr_001" },
  },
  {
    id: "te_010",
    propertyId: "prop_001",
    type: "atos_insight",
    title: "ATOS Alert: Claim Discrepancy Requires Action",
    description: "ATOS identified a $149,000 discrepancy between forensic assessment and carrier approval. Recommended actions generated.",
    date: new Date("2026-02-01"),
    actorId: null,
    actorName: "ATOS",
    metadata: { insightId: "insight_001" },
  },
];

// ─── Dashboard Metrics ──────────────────────────────────────────────────────

export const mockDashboardMetrics: DashboardMetrics = {
  totalProperties: 4,
  activeInspections: 0,
  pendingClaims: 2,
  activeRestorations: 1,
  totalEquityGained: 1361000,
  averageEquityGainPercentage: 26.7,
  criticalAlerts: 2,
};
