bot:
  name: "BuildBot"
  version: "1.0.0"
  enabled: true
  description: "Automated build and compilation of code"
  category: "development"

triggers:
  - type: "event"
    pattern: "code.committed"
    filter: "branch in ['main', 'develop', 'release/*']"
    priority: "high"
  
  - type: "webhook"
    pattern: "/webhook/build"
    priority: "medium"

actions:
  - name: "checkout_code"
    type: "execute"
    command: "git checkout ${branch}"
    timeout: 60
    on_success: "install_dependencies"
    on_failure: "notify_failure"
    
  - name: "install_dependencies"
    type: "execute"
    command: "npm ci"
    timeout: 300
    on_success: "run_build"
    on_failure: "notify_failure"
    
  - name: "run_build"
    type: "execute"
    command: "npm run build"
    timeout: 600
    on_success: "archive_artifacts"
    on_failure: "notify_failure"
    
  - name: "archive_artifacts"
    type: "execute"
    command: "tar -czf build-${build_id}.tar.gz dist/"
    timeout: 120
    on_success: "publish_artifacts"
    
  - name: "publish_artifacts"
    type: "execute"
    command: "aws s3 cp build-${build_id}.tar.gz s3://artifacts/"
    timeout: 300
    on_success: "notify_success"
    
  - name: "notify_success"
    type: "message"
    command: "send_message"
    parameters:
      event: "build.completed"
      payload:
        build_id: "${build_id}"
        artifact_url: "s3://artifacts/build-${build_id}.tar.gz"
        
  - name: "notify_failure"
    type: "message"
    command: "send_message"
    parameters:
      event: "build.failed"
      severity: "critical"

constraints:
  max_concurrent_jobs: 5
  timeout: 1800
  rate_limit:
    requests_per_minute: 20
    burst_size: 10
  retry_policy:
    max_attempts: 2
    backoff: "exponential"
    initial_delay: 10
    max_delay: 300
  resource_limits:
    cpu: "4000m"
    memory: "8Gi"

dependencies:
  required: []
  optional:
    - "LintBot"
  conflicts: []

outputs:
  - type: "message"
    destination: "TestBot"
    format: "json"
    
  - type: "file"
    destination: "s3://artifacts/"
    format: "tar.gz"
    retention: 30
    
  - type: "metric"
    destination: "prometheus"
    format: "openmetrics"

security:
  permissions:
    - resource: "git-repository"
      actions: ["read"]
    - resource: "s3://artifacts/"
      actions: ["write"]
  encryption:
    enabled: true
    algorithm: "AES-256"
  authentication:
    method: "token"

monitoring:
  health_check:
    enabled: true
    interval: 30
    endpoint: "/health"
  metrics:
    enabled: true
    push_interval: 60
  logging:
    level: "info"
    format: "json"

notifications:
  - event: "build.failed"
    channels: ["slack", "email"]
    severity: "critical"
    template: "Build failed for ${branch} - ${error_message}"
    
  - event: "build.completed"
    channels: ["slack"]
    severity: "info"
    template: "Build completed for ${branch} - Artifact: ${artifact_url}"
