bot:
  name: "DeployBot"
  version: "1.0.0"
  enabled: true
  description: "Automated deployment and release management"
  category: "operations"

triggers:
  - type: "event"
    pattern: "test.completed"
    filter: "branch == 'main' and coverage >= 80"
    priority: "high"
    
  - type: "manual"
    pattern: "/deploy"
    priority: "critical"

actions:
  - name: "validate_prerequisites"
    type: "execute"
    command: "./scripts/validate-deploy.sh ${environment}"
    timeout: 120
    on_success: "create_backup"
    on_failure: "notify_failure"
    
  - name: "create_backup"
    type: "execute"
    command: "./scripts/backup-current.sh ${environment}"
    timeout: 600
    on_success: "download_artifacts"
    
  - name: "download_artifacts"
    type: "execute"
    command: "aws s3 cp ${artifact_url} ./deploy.tar.gz"
    timeout: 300
    on_success: "deploy_application"
    
  - name: "deploy_application"
    type: "execute"
    command: "kubectl apply -f k8s/${environment}/"
    timeout: 900
    on_success: "wait_for_rollout"
    on_failure: "rollback_deployment"
    
  - name: "wait_for_rollout"
    type: "execute"
    command: "kubectl rollout status deployment/app -n ${environment}"
    timeout: 600
    on_success: "run_smoke_tests"
    on_failure: "rollback_deployment"
    
  - name: "run_smoke_tests"
    type: "execute"
    command: "./scripts/smoke-tests.sh ${environment}"
    timeout: 300
    on_success: "notify_success"
    on_failure: "rollback_deployment"
    
  - name: "rollback_deployment"
    type: "execute"
    command: "kubectl rollout undo deployment/app -n ${environment}"
    timeout: 600
    on_success: "notify_rollback"
    
  - name: "notify_success"
    type: "message"
    command: "send_message"
    parameters:
      event: "deploy.completed"
      payload:
        environment: "${environment}"
        version: "${version}"
        
  - name: "notify_failure"
    type: "message"
    command: "send_message"
    parameters:
      event: "deploy.failed"
      severity: "critical"
      
  - name: "notify_rollback"
    type: "message"
    command: "send_message"
    parameters:
      event: "deploy.rolled_back"
      severity: "warning"

constraints:
  max_concurrent_jobs: 1  # Only one deployment at a time
  timeout: 3600
  rate_limit:
    requests_per_minute: 5
    burst_size: 2
  retry_policy:
    max_attempts: 1  # No automatic retries for deployments
    backoff: "fixed"
  resource_limits:
    cpu: "2000m"
    memory: "4Gi"

dependencies:
  required:
    - "TestBot"
    - "BackupBot"
  optional:
    - "MonitorBot"
  conflicts: []

outputs:
  - type: "message"
    destination: "MonitorBot"
    format: "json"
    
  - type: "file"
    destination: "s3://deployment-logs/"
    format: "text"
    retention: 365
    
  - type: "metric"
    destination: "prometheus"
    format: "openmetrics"

security:
  permissions:
    - resource: "kubernetes-cluster"
      actions: ["deploy", "rollback"]
    - resource: "s3://artifacts/"
      actions: ["read"]
    - resource: "s3://deployment-logs/"
      actions: ["write"]
  encryption:
    enabled: true
    algorithm: "AES-256"
  authentication:
    method: "certificate"

monitoring:
  health_check:
    enabled: true
    interval: 30
    endpoint: "/health"
  metrics:
    enabled: true
    push_interval: 30
  logging:
    level: "info"
    format: "json"

notifications:
  - event: "deploy.failed"
    channels: ["slack", "email", "pagerduty"]
    severity: "critical"
    template: "Deployment to ${environment} FAILED - ${error_message}"
    
  - event: "deploy.rolled_back"
    channels: ["slack", "email"]
    severity: "warning"
    template: "Deployment to ${environment} rolled back - Previous version restored"
    
  - event: "deploy.completed"
    channels: ["slack"]
    severity: "info"
    template: "Successfully deployed ${version} to ${environment}"
