bot:
  name: "TestBot"
  version: "1.0.0"
  enabled: true
  description: "Automated testing and quality validation"
  category: "development"

triggers:
  - type: "event"
    pattern: "build.completed"
    priority: "high"
    
  - type: "schedule"
    pattern: "0 2 * * *"  # Daily at 2 AM
    priority: "low"

actions:
  - name: "download_artifacts"
    type: "execute"
    command: "aws s3 cp ${artifact_url} ./build.tar.gz"
    timeout: 300
    on_success: "extract_artifacts"
    
  - name: "extract_artifacts"
    type: "execute"
    command: "tar -xzf build.tar.gz"
    timeout: 60
    on_success: "run_unit_tests"
    
  - name: "run_unit_tests"
    type: "execute"
    command: "npm test -- --unit"
    timeout: 600
    on_success: "run_integration_tests"
    on_failure: "report_failure"
    
  - name: "run_integration_tests"
    type: "execute"
    command: "npm test -- --integration"
    timeout: 1800
    on_success: "run_e2e_tests"
    on_failure: "report_failure"
    
  - name: "run_e2e_tests"
    type: "execute"
    command: "npm test -- --e2e"
    timeout: 3600
    on_success: "generate_coverage"
    on_failure: "report_failure"
    
  - name: "generate_coverage"
    type: "execute"
    command: "npm run coverage"
    timeout: 300
    on_success: "publish_results"
    
  - name: "publish_results"
    type: "execute"
    command: "aws s3 cp coverage/ s3://test-results/ --recursive"
    timeout: 300
    on_success: "notify_success"
    
  - name: "notify_success"
    type: "message"
    command: "send_message"
    parameters:
      event: "test.completed"
      payload:
        total_tests: "${total_tests}"
        passed_tests: "${passed_tests}"
        coverage: "${coverage_percent}"
        
  - name: "report_failure"
    type: "message"
    command: "send_message"
    parameters:
      event: "test.failed"
      severity: "critical"

constraints:
  max_concurrent_jobs: 3
  timeout: 7200
  rate_limit:
    requests_per_minute: 10
    burst_size: 5
  retry_policy:
    max_attempts: 2
    backoff: "exponential"
    initial_delay: 30
    max_delay: 600
  resource_limits:
    cpu: "4000m"
    memory: "8Gi"

dependencies:
  required:
    - "BuildBot"
  optional:
    - "LintBot"
  conflicts: []

outputs:
  - type: "message"
    destination: "DeployBot"
    format: "json"
    
  - type: "file"
    destination: "s3://test-results/"
    format: "junit-xml"
    retention: 90
    
  - type: "metric"
    destination: "prometheus"
    format: "openmetrics"

security:
  permissions:
    - resource: "s3://artifacts/"
      actions: ["read"]
    - resource: "s3://test-results/"
      actions: ["write"]
    - resource: "test-database"
      actions: ["read", "write"]
  encryption:
    enabled: true
    algorithm: "AES-256"
  authentication:
    method: "token"

monitoring:
  health_check:
    enabled: true
    interval: 30
    endpoint: "/health"
  metrics:
    enabled: true
    push_interval: 60
  logging:
    level: "info"
    format: "json"

notifications:
  - event: "test.failed"
    channels: ["slack", "email"]
    severity: "critical"
    template: "Tests failed - ${failed_tests}/${total_tests} failures"
    
  - event: "test.completed"
    channels: ["slack"]
    severity: "info"
    template: "Tests passed - ${passed_tests}/${total_tests} - Coverage: ${coverage_percent}%"
