/**
 * Mock data for development and demonstration.
 * 
 * WHY: We need realistic data to build and validate the UI before
 * connecting to the real database. This data models real-world
 * commercial storm damage scenarios with plausible values.
 * 
 * All mock data will be replaced by Postgres queries in production.
 */

import type {
  User,
  Property,
  Inspection,
  InsuranceClaim,
  Contractor,
  ScopeAssignment,
  EquityOutcome,
  DashboardStats,
  TimelineEvent,
  AtosInsight,
  Evidence,
  CarrierInteraction,
  ScopeItem,
} from "@/types";

// ─── Current User ──────────────────────────────────────────

export const currentUser: User = {
  id: "usr_001",
  email: "sarah.mitchell@equitybuilders.com",
  name: "Sarah Mitchell",
  role: "internal",
  organization: "Equity Builders",
  createdAt: "2024-01-15T00:00:00Z",
  lastLoginAt: "2026-02-09T08:30:00Z",
};

// ─── Properties ────────────────────────────────────────────

export const properties: Property[] = [
  {
    id: "prop_001",
    name: "Meridian Business Center",
    address: "4200 Meridian Blvd",
    city: "Dallas",
    state: "TX",
    zip: "75201",
    propertyType: "office",
    status: "negotiation",
    ownerId: "usr_010",
    squareFootage: 42000,
    yearBuilt: 1998,
    estimatedValue: 4200000,
    stormDate: "2025-11-15",
    stormType: "Hailstorm — Category 3",
    createdAt: "2025-11-20T00:00:00Z",
    updatedAt: "2026-02-08T00:00:00Z",
  },
  {
    id: "prop_002",
    name: "Westfield Industrial Complex",
    address: "8900 Industrial Way",
    city: "Fort Worth",
    state: "TX",
    zip: "76102",
    propertyType: "industrial",
    status: "in_repair",
    ownerId: "usr_011",
    squareFootage: 85000,
    yearBuilt: 2005,
    estimatedValue: 6800000,
    stormDate: "2025-10-02",
    stormType: "Straight-line winds — 90mph",
    createdAt: "2025-10-10T00:00:00Z",
    updatedAt: "2026-02-07T00:00:00Z",
  },
  {
    id: "prop_003",
    name: "Lakewood Retail Plaza",
    address: "1500 Lakewood Dr",
    city: "Plano",
    state: "TX",
    zip: "75023",
    propertyType: "retail",
    status: "equity_verified",
    ownerId: "usr_012",
    squareFootage: 28000,
    yearBuilt: 2010,
    estimatedValue: 3500000,
    stormDate: "2025-06-20",
    stormType: "Hailstorm — Category 2",
    createdAt: "2025-06-25T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "prop_004",
    name: "Summit Mixed-Use Tower",
    address: "2200 Commerce St",
    city: "Houston",
    state: "TX",
    zip: "77002",
    propertyType: "mixed-use",
    status: "inspection",
    ownerId: "usr_013",
    squareFootage: 120000,
    yearBuilt: 2015,
    estimatedValue: 18500000,
    stormDate: "2026-01-28",
    stormType: "Hurricane remnants — wind + water",
    createdAt: "2026-01-30T00:00:00Z",
    updatedAt: "2026-02-09T00:00:00Z",
  },
  {
    id: "prop_005",
    name: "Riverside Office Park",
    address: "750 River Rd",
    city: "Austin",
    state: "TX",
    zip: "78701",
    propertyType: "office",
    status: "claim_filed",
    ownerId: "usr_014",
    squareFootage: 35000,
    yearBuilt: 2002,
    estimatedValue: 5100000,
    stormDate: "2025-12-10",
    stormType: "Tornado — EF1",
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2026-02-05T00:00:00Z",
  },
  {
    id: "prop_006",
    name: "Heritage Commercial Building",
    address: "320 Main St",
    city: "San Antonio",
    state: "TX",
    zip: "78205",
    propertyType: "commercial",
    status: "assessment",
    ownerId: "usr_015",
    squareFootage: 18000,
    yearBuilt: 1985,
    estimatedValue: 2200000,
    stormDate: "2026-01-05",
    stormType: "Hailstorm — Category 4",
    createdAt: "2026-01-08T00:00:00Z",
    updatedAt: "2026-02-08T00:00:00Z",
  },
];

// ─── Inspections ───────────────────────────────────────────

export const inspections: Inspection[] = [
  {
    id: "insp_001",
    propertyId: "prop_001",
    inspectorName: "James Thornton, PE",
    inspectionDate: "2025-11-25",
    findings: "Extensive hail impact across entire TPO roof membrane. 47 confirmed impact points per test square. Perimeter flashings compromised at NW and SE corners. 3 rooftop HVAC units show significant cabinet and coil damage. Interior water intrusion confirmed in 4 offices on the 3rd floor. Fascia and soffit damage noted on south elevation.",
    damageClassifications: ["hail", "roof", "hvac", "water", "facade"],
    severity: "severe",
    estimatedRepairCost: 892000,
    photoCount: 247,
    documentCount: 12,
    status: "completed",
    createdAt: "2025-11-25T00:00:00Z",
  },
  {
    id: "insp_002",
    propertyId: "prop_002",
    inspectorName: "Maria Santos, RRC",
    inspectionDate: "2025-10-15",
    findings: "Wind damage to standing seam metal roof on Building A. Multiple panels displaced and seam separations observed. Loading dock doors on Building B structurally compromised. Warehouse interior shows water damage to inventory staging areas. Electrical panel damage on Building C from power surge.",
    damageClassifications: ["wind", "structural", "water", "electrical"],
    severity: "severe",
    estimatedRepairCost: 1450000,
    photoCount: 312,
    documentCount: 18,
    status: "completed",
    createdAt: "2025-10-15T00:00:00Z",
  },
  {
    id: "insp_003",
    propertyId: "prop_004",
    inspectorName: "Robert Chen, PE",
    inspectionDate: "2026-02-05",
    findings: "Initial forensic inspection of hurricane damage. Significant water intrusion through curtain wall system on floors 8-12. Roof membrane fully compromised with standing water. Ground floor retail spaces show 18 inches of flood damage. Elevator mechanical room flooded. Full structural assessment pending.",
    damageClassifications: ["water", "wind", "structural", "electrical"],
    severity: "catastrophic",
    estimatedRepairCost: 4200000,
    photoCount: 89,
    documentCount: 5,
    status: "in_progress",
    createdAt: "2026-02-05T00:00:00Z",
  },
];

// ─── Insurance Claims ──────────────────────────────────────

export const insuranceClaims: InsuranceClaim[] = [
  {
    id: "claim_001",
    propertyId: "prop_001",
    claimNumber: "HIC-2025-78432",
    carrier: "Hartford Commercial Insurance",
    policyNumber: "HCI-COM-445892",
    filedDate: "2025-12-01",
    status: "under_review",
    claimedAmount: 892000,
    deductible: 25000,
    adjusterName: "Tom Bridges",
    adjusterEmail: "tbridges@hartford.com",
    adjusterPhone: "(214) 555-0189",
    lastContactDate: "2026-02-03",
    nextActionDate: "2026-02-12",
    notes: "Carrier acknowledged hail damage but disputing HVAC replacement scope. Requesting independent engineer review of 3 rooftop units. We have manufacturer documentation showing irreparable coil damage.",
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-02-08T00:00:00Z",
  },
  {
    id: "claim_002",
    propertyId: "prop_002",
    claimNumber: "SFC-2025-91205",
    carrier: "State Farm Commercial",
    policyNumber: "SFC-IND-772341",
    filedDate: "2025-10-20",
    status: "approved",
    claimedAmount: 1450000,
    approvedAmount: 1280000,
    deductible: 50000,
    adjusterName: "Lisa Park",
    adjusterEmail: "lpark@statefarm.com",
    adjusterPhone: "(817) 555-0234",
    lastContactDate: "2026-01-20",
    notes: "Claim approved after second supplemental. Original scope was $980K, supplemented twice. Loading dock replacement fully covered. Disputing remaining $170K for electrical panel upgrades — carrier says pre-existing, we have pre-storm electrical inspection report proving otherwise.",
    createdAt: "2025-10-20T00:00:00Z",
    updatedAt: "2026-01-20T00:00:00Z",
  },
  {
    id: "claim_003",
    propertyId: "prop_003",
    claimNumber: "TIC-2025-65890",
    carrier: "Travelers Insurance Company",
    policyNumber: "TIC-RET-334567",
    filedDate: "2025-07-01",
    status: "settled",
    claimedAmount: 485000,
    approvedAmount: 462000,
    deductible: 15000,
    adjusterName: "Kevin Walsh",
    adjusterEmail: "kwalsh@travelers.com",
    adjusterPhone: "(972) 555-0312",
    lastContactDate: "2025-12-15",
    notes: "Claim fully settled. Excellent outcome — 95.3% claim-to-payout ratio. Carrier was responsive throughout. All documentation verified and accepted on first submission.",
    createdAt: "2025-07-01T00:00:00Z",
    updatedAt: "2025-12-15T00:00:00Z",
  },
  {
    id: "claim_004",
    propertyId: "prop_005",
    claimNumber: "ACE-2025-44321",
    carrier: "Ace American Insurance",
    policyNumber: "ACE-COM-998765",
    filedDate: "2025-12-20",
    status: "submitted",
    claimedAmount: 780000,
    deductible: 35000,
    adjusterName: "Pending Assignment",
    lastContactDate: "2025-12-22",
    nextActionDate: "2026-02-15",
    notes: "Claim filed with full forensic inspection report. Awaiting adjuster assignment. Tornado damage documentation is strong — NOAA weather data confirms EF1 tornado path directly over property.",
    createdAt: "2025-12-20T00:00:00Z",
    updatedAt: "2025-12-22T00:00:00Z",
  },
];

// ─── Carrier Interactions ──────────────────────────────────

export const carrierInteractions: CarrierInteraction[] = [
  {
    id: "ci_001",
    claimId: "claim_001",
    date: "2026-02-03",
    type: "call",
    summary: "Adjuster Bridges called to request additional documentation on HVAC damage. Specifically wants manufacturer specs showing coil damage threshold. We confirmed we have Trane engineering bulletin TB-2024-003 documenting that coil fin damage exceeding 30% surface area constitutes irreparable damage.",
    participants: ["Tom Bridges (Hartford)", "Sarah Mitchell (EB)"],
    outcome: "Agreed to submit supplemental with Trane documentation by Feb 10",
    followUpRequired: true,
    followUpDate: "2026-02-10",
    documentIds: ["ev_012", "ev_013"],
  },
  {
    id: "ci_002",
    claimId: "claim_001",
    date: "2026-01-15",
    type: "site_visit",
    summary: "Carrier's independent adjuster conducted site inspection. We provided guided access to all documented damage areas. Adjuster agreed roof damage is hail-related but initially classified HVAC damage as 'cosmetic.' Our forensic documentation showing performance degradation post-impact was presented on-site.",
    participants: ["Tom Bridges (Hartford)", "James Thornton, PE", "Sarah Mitchell (EB)"],
    outcome: "Carrier agreed to re-evaluate HVAC scope with engineering data",
    followUpRequired: true,
    followUpDate: "2026-02-01",
    documentIds: ["ev_008", "ev_009", "ev_010"],
  },
];

// ─── Scope Items ───────────────────────────────────────────

export const scopeItems: ScopeItem[] = [
  {
    id: "si_001",
    claimId: "claim_001",
    category: "Roofing",
    description: "Full TPO roof membrane replacement — 42,000 sq ft",
    ownerEstimate: 420000,
    carrierEstimate: 395000,
    discrepancy: 25000,
    notes: "Minor discrepancy on material grade specification",
  },
  {
    id: "si_002",
    claimId: "claim_001",
    category: "HVAC",
    description: "Replacement of 3 rooftop Trane units (25-ton each)",
    ownerEstimate: 285000,
    carrierEstimate: 45000,
    discrepancy: 240000,
    notes: "CRITICAL DISCREPANCY: Carrier classifying as cosmetic repair only. We have Trane documentation proving irreparable coil damage.",
  },
  {
    id: "si_003",
    claimId: "claim_001",
    category: "Interior",
    description: "Water damage remediation — 3rd floor offices (4 rooms)",
    ownerEstimate: 95000,
    carrierEstimate: 88000,
    discrepancy: 7000,
  },
  {
    id: "si_004",
    claimId: "claim_001",
    category: "Exterior",
    description: "Fascia and soffit replacement — south elevation",
    ownerEstimate: 52000,
    carrierEstimate: 48000,
    discrepancy: 4000,
  },
  {
    id: "si_005",
    claimId: "claim_001",
    category: "Flashings",
    description: "Perimeter flashing replacement — NW and SE corners",
    ownerEstimate: 40000,
    carrierEstimate: 38000,
    discrepancy: 2000,
  },
];

// ─── Contractors ───────────────────────────────────────────

export const contractors: Contractor[] = [
  {
    id: "con_001",
    name: "Mike Davidson",
    company: "Davidson Commercial Roofing",
    email: "mike@davidsonroofing.com",
    phone: "(214) 555-0156",
    licenseNumber: "TX-CRC-44892",
    insuranceVerified: true,
    specializations: ["commercial roofing", "TPO", "metal roofing", "flat roof systems"],
    rating: 4.9,
    completedJobs: 47,
    status: "active",
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "con_002",
    name: "Elena Rodriguez",
    company: "Rodriguez HVAC Solutions",
    email: "elena@rodriguezhvac.com",
    phone: "(817) 555-0278",
    licenseNumber: "TX-HVAC-67123",
    insuranceVerified: true,
    specializations: ["commercial HVAC", "rooftop units", "Trane certified", "Carrier certified"],
    rating: 4.8,
    completedJobs: 31,
    status: "active",
    createdAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "con_003",
    name: "David Kim",
    company: "Kim General Contracting",
    email: "david@kimgc.com",
    phone: "(972) 555-0345",
    licenseNumber: "TX-GC-89234",
    insuranceVerified: true,
    specializations: ["interior restoration", "water damage", "commercial buildout", "facade repair"],
    rating: 4.7,
    completedJobs: 62,
    status: "active",
    createdAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "con_004",
    name: "James Fowler",
    company: "Fowler Structural Engineering",
    email: "james@fowlerse.com",
    phone: "(512) 555-0412",
    licenseNumber: "TX-SE-23456",
    insuranceVerified: true,
    specializations: ["structural assessment", "load-bearing repair", "foundation", "seismic retrofit"],
    rating: 4.9,
    completedJobs: 28,
    status: "active",
    createdAt: "2024-09-01T00:00:00Z",
  },
];

// ─── Scope Assignments ─────────────────────────────────────

export const scopeAssignments: ScopeAssignment[] = [
  {
    id: "sa_001",
    propertyId: "prop_002",
    contractorId: "con_001",
    description: "Standing seam metal roof repair and panel replacement — Building A",
    estimatedCost: 680000,
    startDate: "2026-01-15",
    expectedEndDate: "2026-03-15",
    status: "in_progress",
    progressPercentage: 45,
    complianceChecks: [
      { id: "cc_001", name: "Permit Obtained", description: "City of Fort Worth building permit", passed: true, checkedAt: "2026-01-10", checkedBy: "Sarah Mitchell" },
      { id: "cc_002", name: "Material Spec Match", description: "Materials match approved scope specifications", passed: true, checkedAt: "2026-01-14", checkedBy: "James Thornton, PE" },
      { id: "cc_003", name: "Mid-Point Inspection", description: "Independent inspection at 50% completion", passed: false, notes: "Scheduled for Feb 15" },
      { id: "cc_004", name: "Final Inspection", description: "Final code compliance inspection", passed: false },
    ],
  },
  {
    id: "sa_002",
    propertyId: "prop_002",
    contractorId: "con_003",
    description: "Loading dock door replacement and warehouse interior restoration",
    estimatedCost: 380000,
    startDate: "2026-02-01",
    expectedEndDate: "2026-04-01",
    status: "in_progress",
    progressPercentage: 15,
    complianceChecks: [
      { id: "cc_005", name: "Permit Obtained", description: "Structural modification permit", passed: true, checkedAt: "2026-01-28", checkedBy: "Sarah Mitchell" },
      { id: "cc_006", name: "Material Spec Match", description: "Dock door specifications match scope", passed: true, checkedAt: "2026-01-30", checkedBy: "Sarah Mitchell" },
      { id: "cc_007", name: "Mid-Point Inspection", description: "Structural integrity check", passed: false },
      { id: "cc_008", name: "Final Inspection", description: "Final code compliance inspection", passed: false },
    ],
  },
];

// ─── Equity Outcomes ───────────────────────────────────────

export const equityOutcomes: EquityOutcome[] = [
  {
    id: "eq_001",
    propertyId: "prop_003",
    preStormValue: 3500000,
    postRepairValue: 3920000,
    totalClaimAmount: 485000,
    totalPayoutReceived: 462000,
    totalRepairCost: 410000,
    netEquityGain: 472000,
    equityGainPercentage: 13.5,
    narrative: "Lakewood Retail Plaza sustained Category 2 hail damage in June 2025. Through comprehensive forensic documentation and strategic claim management, the property received $462,000 in insurance proceeds against $410,000 in repair costs. The modernized roofing system, updated HVAC, and refreshed facade drove a $420,000 increase in appraised value. Net equity gain of $472,000 represents a 13.5% value increase, transforming storm damage into verified equity growth.",
    verifiedAt: "2026-01-15T00:00:00Z",
    verifiedBy: "Sarah Mitchell",
    createdAt: "2026-01-15T00:00:00Z",
  },
];

// ─── Evidence ──────────────────────────────────────────────

export const evidence: Evidence[] = [
  {
    id: "ev_001",
    propertyId: "prop_001",
    type: "photo",
    title: "Roof Overview — Hail Impact Pattern",
    description: "Aerial view showing systematic hail impact distribution across TPO membrane",
    fileUrl: "/images/placeholder.jpg",
    uploadedBy: "James Thornton, PE",
    uploadedAt: "2025-11-25T10:30:00Z",
    tags: ["roof", "hail", "overview", "aerial"],
  },
  {
    id: "ev_002",
    propertyId: "prop_001",
    type: "photo",
    title: "Test Square #1 — 47 Impacts Documented",
    description: "10x10 test square showing 47 confirmed hail impacts with chalk markings",
    fileUrl: "/images/placeholder.jpg",
    uploadedBy: "James Thornton, PE",
    uploadedAt: "2025-11-25T10:45:00Z",
    tags: ["roof", "hail", "test-square", "detailed"],
  },
  {
    id: "ev_003",
    propertyId: "prop_001",
    type: "document",
    title: "Forensic Inspection Report — Complete",
    description: "Full forensic inspection report with findings, photos, and repair recommendations",
    fileUrl: "/docs/placeholder.pdf",
    uploadedBy: "James Thornton, PE",
    uploadedAt: "2025-12-01T00:00:00Z",
    tags: ["report", "inspection", "forensic"],
  },
  {
    id: "ev_004",
    propertyId: "prop_001",
    type: "document",
    title: "Trane Engineering Bulletin TB-2024-003",
    description: "Manufacturer documentation on coil damage irreparability thresholds",
    fileUrl: "/docs/placeholder.pdf",
    uploadedBy: "Sarah Mitchell",
    uploadedAt: "2026-01-20T00:00:00Z",
    tags: ["hvac", "manufacturer", "technical", "evidence"],
  },
];

// ─── ATOS Insights ─────────────────────────────────────────

export const atosInsights: AtosInsight[] = [
  {
    id: "ai_001",
    propertyId: "prop_001",
    category: "risk",
    title: "HVAC Scope Discrepancy — $240K at Risk",
    description: "Hartford is disputing $240,000 in HVAC replacement costs by classifying damage as cosmetic. This is the largest scope discrepancy in this claim. The Trane engineering bulletin TB-2024-003 directly contradicts the carrier's position. Recommend submitting supplemental documentation with manufacturer specifications by February 10.",
    severity: "critical",
    actionRequired: true,
    suggestedAction: "Prepare and submit HVAC supplemental package with Trane documentation, performance test results, and independent engineer affidavit.",
    createdAt: "2026-02-08T00:00:00Z",
    acknowledged: false,
  },
  {
    id: "ai_002",
    propertyId: "prop_001",
    category: "opportunity",
    title: "Code Upgrade Opportunity — Roof Ventilation",
    description: "Current building code requires improved roof ventilation compared to the 1998 original installation. Because the roof is being fully replaced, code-required upgrades should be included in the scope and are typically carrier-covered as 'code upgrades.' This could add $35,000-$45,000 to the approved scope.",
    severity: "medium",
    actionRequired: true,
    suggestedAction: "Add code-required ventilation upgrades to the claim supplemental. Reference Texas Building Code Section 1203.2.",
    createdAt: "2026-02-07T00:00:00Z",
    acknowledged: false,
  },
  {
    id: "ai_003",
    propertyId: "prop_004",
    category: "gap",
    title: "Incomplete Inspection — Floors 1-7 Not Yet Assessed",
    description: "The initial inspection covered floors 8-12 and the roof, but floors 1-7 have not been forensically assessed. Given that hurricane remnants caused water intrusion from above and flooding from below, lower floors may have concealed damage in wall cavities, flooring substrate, and electrical systems.",
    severity: "high",
    actionRequired: true,
    suggestedAction: "Schedule comprehensive inspection of floors 1-7 with focus on concealed water damage, mold potential, and electrical system integrity.",
    createdAt: "2026-02-06T00:00:00Z",
    acknowledged: false,
  },
  {
    id: "ai_004",
    propertyId: "prop_002",
    category: "milestone",
    title: "Roofing Progress On Track — 45% Complete",
    description: "Davidson Commercial Roofing has reached 45% completion on Building A roof repair. Progress is on schedule for the March 15 target. Mid-point inspection is scheduled for February 15. Material specifications have been verified as matching the approved scope.",
    severity: "info",
    actionRequired: false,
    createdAt: "2026-02-09T00:00:00Z",
    acknowledged: true,
  },
  {
    id: "ai_005",
    category: "recommendation",
    title: "Portfolio-Wide: 3 Properties Approaching Claim Deadlines",
    description: "Based on Texas insurance claim filing requirements, 3 properties in the current portfolio are within 60 days of supplemental filing deadlines. Prioritize documentation completion for Meridian Business Center (Feb 28), Riverside Office Park (Mar 10), and Heritage Commercial Building (Mar 15).",
    severity: "high",
    actionRequired: true,
    suggestedAction: "Review and prioritize supplemental documentation for all 3 properties. Assign dedicated resources to ensure timely filing.",
    createdAt: "2026-02-09T00:00:00Z",
    acknowledged: false,
  },
];

// ─── Timeline Events ───────────────────────────────────────

export const timelineEvents: TimelineEvent[] = [
  {
    id: "te_001",
    propertyId: "prop_001",
    timestamp: "2026-02-08T14:30:00Z",
    type: "atos_insight",
    title: "ATOS flagged critical HVAC scope discrepancy",
    description: "$240K HVAC replacement at risk — carrier disputing as cosmetic damage",
  },
  {
    id: "te_002",
    propertyId: "prop_001",
    timestamp: "2026-02-03T10:15:00Z",
    type: "claim",
    title: "Carrier call — HVAC documentation request",
    description: "Hartford adjuster requested manufacturer specs for HVAC coil damage threshold",
  },
  {
    id: "te_003",
    propertyId: "prop_001",
    timestamp: "2026-01-20T09:00:00Z",
    type: "evidence",
    title: "Trane Engineering Bulletin uploaded",
    description: "TB-2024-003 documenting irreparable coil damage thresholds",
  },
  {
    id: "te_004",
    propertyId: "prop_001",
    timestamp: "2026-01-15T14:00:00Z",
    type: "claim",
    title: "Carrier site inspection completed",
    description: "Hartford independent adjuster conducted on-site damage assessment",
  },
  {
    id: "te_005",
    propertyId: "prop_001",
    timestamp: "2025-12-01T00:00:00Z",
    type: "claim",
    title: "Insurance claim filed",
    description: "Claim HIC-2025-78432 submitted to Hartford Commercial Insurance for $892,000",
  },
  {
    id: "te_006",
    propertyId: "prop_001",
    timestamp: "2025-11-25T00:00:00Z",
    type: "inspection",
    title: "Forensic inspection completed",
    description: "James Thornton, PE completed full forensic assessment — severe hail damage confirmed",
  },
  {
    id: "te_007",
    propertyId: "prop_001",
    timestamp: "2025-11-20T00:00:00Z",
    type: "milestone",
    title: "Property intake completed",
    description: "Meridian Business Center entered into Equity Builders platform",
  },
];

// ─── Dashboard Stats ───────────────────────────────────────

export const dashboardStats: DashboardStats = {
  totalProperties: 6,
  activeInspections: 2,
  pendingClaims: 3,
  totalEquityGained: 472000,
  averageClaimCycle: 142,
  claimApprovalRate: 94.2,
  activeContractors: 4,
  propertiesInRepair: 1,
};
